2023-11-08T16:39:08.970693+00:00 app[worker.1]:     return await mystic(_, message, language)
2023-11-08T16:39:08.970694+00:00 app[worker.1]:   File "/app/InflexMusic/plugins/bot/start.py", line 89, in start_pm
2023-11-08T16:39:08.970694+00:00 app[worker.1]:     await message.reply_photo(
2023-11-08T16:39:08.970694+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2000, in reply_photo
2023-11-08T16:39:08.970695+00:00 app[worker.1]:     return await self._client.send_photo(
2023-11-08T16:39:08.970695+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/send_photo.py", line 166, in send_photo
2023-11-08T16:39:08.970695+00:00 app[worker.1]:     media = utils.get_input_media_from_file_id(photo, FileType.PHOTO, ttl_seconds=ttl_seconds)
2023-11-08T16:39:08.970696+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/utils.py", line 51, in get_input_media_from_file_id
2023-11-08T16:39:08.970696+00:00 app[worker.1]:     raise ValueError(
2023-11-08T16:39:08.970696+00:00 app[worker.1]: ValueError: Failed to decode "9". The value does not represent an existing local file, HTTP URL, or valid file id.
2023-11-08T16:43:19.939389+00:00 app[worker.1]: 
2023-11-08T16:43:19.939398+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2023-11-08T16:43:19.939400+00:00 app[worker.1]: 
2023-11-08T16:43:19.939401+00:00 app[worker.1]: [93mUpdate Available!
2023-11-08T16:43:19.939401+00:00 app[worker.1]: New PyTgCalls v1.0.1 is now available!
2023-11-08T16:43:19.939402+00:00 app[worker.1]: [0m
2023-11-08T16:43:19.939402+00:00 app[worker.1]: [32m [6559287964] Started Node.js core! [0m
2023-11-08T16:48:45.502039+00:00 app[worker.1]: 
2023-11-08T16:48:45.502052+00:00 app[worker.1]: Traceback (most recent call last):
2023-11-08T16:48:45.502053+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/utils.py", line 49, in get_input_media_from_file_id
2023-11-08T16:48:45.502053+00:00 app[worker.1]:     decoded = FileId.decode(file_id)
2023-11-08T16:48:45.502054+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/file_id.py", line 201, in decode
2023-11-08T16:48:45.502055+00:00 app[worker.1]:     decoded = rle_decode(b64_decode(file_id))
2023-11-08T16:48:45.502055+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/file_id.py", line 54, in b64_decode
2023-11-08T16:48:45.502056+00:00 app[worker.1]:     return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))
2023-11-08T16:48:45.502057+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
2023-11-08T16:48:45.502072+00:00 app[worker.1]:     return b64decode(s)
2023-11-08T16:48:45.502072+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/base64.py", line 87, in b64decode
2023-11-08T16:48:45.502073+00:00 app[worker.1]:     return binascii.a2b_base64(s)
2023-11-08T16:48:45.502073+00:00 app[worker.1]: binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
2023-11-08T16:48:45.502074+00:00 app[worker.1]: 
2023-11-08T16:48:45.502075+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2023-11-08T16:48:45.502075+00:00 app[worker.1]: 
2023-11-08T16:48:45.502075+00:00 app[worker.1]: Traceback (most recent call last):
2023-11-08T16:48:45.502075+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2023-11-08T16:48:45.502075+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2023-11-08T16:48:45.502075+00:00 app[worker.1]:   File "/app/InflexMusic/utils/decorators/language.py", line 54, in wrapper
2023-11-08T16:48:45.502076+00:00 app[worker.1]:     return await mystic(_, message, language)
2023-11-08T16:48:45.502076+00:00 app[worker.1]:   File "/app/InflexMusic/plugins/bot/start.py", line 89, in start_pm
2023-11-08T16:48:45.502077+00:00 app[worker.1]:     await message.reply_photo(
2023-11-08T16:48:45.502078+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2000, in reply_photo
2023-11-08T16:48:45.502078+00:00 app[worker.1]:     return await self._client.send_photo(
2023-11-08T16:48:45.502078+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/send_photo.py", line 166, in send_photo
2023-11-08T16:48:45.502078+00:00 app[worker.1]:     media = utils.get_input_media_from_file_id(photo, FileType.PHOTO, ttl_seconds=ttl_seconds)
2023-11-08T16:48:45.502078+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/site-packages/pyrogram/utils.py", line 51, in get_input_media_from_file_id
2023-11-08T16:48:45.502078+00:00 app[worker.1]:     raise ValueError(
2023-11-08T16:48:45.502079+00:00 app[worker.1]: ValueError: Failed to decode "5". The value does not represent an existing local file, HTTP URL, or valid file id.